language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
    - /^v1.*$/
script:
  - npm run build
deploy:
  - provider: surge
    project: ./build/
    domain: upstamps.com
    skip_cleanup: true
    on:
      tags: true
