import React from "react";
//Styles
import styled from "styled-components";
import DocumentStyles from "../../styles/Document";

function Privacy({ className }: { className?: string }) {
  return (
    <div className={className}>
      <div className="content">
        <h1>PRIVACY POLICY</h1>
        <p>Effective date: 19/04/2020</p>
        <p>Last updated: 19/04/2020</p>
        <ol>
          <li>
            <strong>
              <u>Introduction</u>
            </strong>
          </li>
        </ol>
        <p>
          Welcome to&nbsp;<strong>UpStamps</strong>
        </p>
        <p>
          UpStamps&nbsp;(&ldquo;us&rdquo;, &ldquo;we&rdquo;, or
          &ldquo;our&rdquo;) operates&nbsp;
          <a
            rel="noopener noreferrer"
            href="https://www.upstamps.com"
            target="_blank"
          >
            https://www.upstamps.com
          </a>
          &nbsp;(hereinafter referred to as &ldquo;<strong>Service</strong>
          &rdquo;).
        </p>
        <p>
          Our Privacy Policy governs your visit to&nbsp;{" "}
          <a
            rel="noopener noreferrer"
            href="https://www.upstamps.com"
            target="_blank"
          >
            https://www.upstamps.com
          </a>
          , and explains how we collect, safeguard and disclose information that
          results from your use of our Service.
        </p>
        <p>
          We use your data to provide and improve Service. By using Service, you
          agree to the collection and use of information in accordance with this
          policy. Unless otherwise defined in this Privacy Policy, the terms
          used in this Privacy Policy have the same meanings as in our Terms and
          Conditions.
        </p>
        <p>
          Our Terms and Conditions (&ldquo;<strong>Terms</strong>&rdquo;) govern
          all use of our Service and together with the Privacy Policy
          constitutes your agreement with us (&ldquo;<strong>agreement</strong>
          &rdquo;).
        </p>
        <ol start={2}>
          <li>
            <strong>
              <u>Definitions</u>
            </strong>
          </li>
        </ol>
        <p>
          <strong>SERVICE&nbsp;</strong>means the&nbsp;{" "}
          <a
            rel="noopener noreferrer"
            href="https://www.upstamps.com"
            target="_blank"
          >
            https://www.upstamps.com
          </a>
          &nbsp; website&nbsp;operated by&nbsp;UpStamps
        </p>
        <p>
          <strong>PERSONAL DATA</strong>&nbsp;means data about a living
          individual who can be identified from those data (or from those and
          other information either in our possession or likely to come into our
          possession).
        </p>
        <p>
          <strong>USAGE DATA</strong>&nbsp;is data collected automatically
          either generated by the use of Service or from Service infrastructure
          itself (for example, the duration of a page visit).
        </p>
        <p>
          <strong>COOKIES</strong>&nbsp;are small files stored on your device
          (computer or mobile device).
        </p>
        <p>
          <strong>DATA CONTROLLER</strong>&nbsp;means a natural or legal person
          who (either alone or jointly or in common with other persons)
          determines the purposes for which and the manner in which any personal
          data are, or are to be, processed. For the purpose of this Privacy
          Policy, we are a Data Controller of your data.
        </p>
        <p>
          <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong>&nbsp;means any
          natural or legal person who processes the data on behalf of the Data
          Controller. We may use the services of various Service Providers in
          order to process your data more effectively.
        </p>
        <p>
          <strong>DATA SUBJECT&nbsp;</strong>is any living individual who is the
          subject of Personal Data.
        </p>
        <p>
          <strong>THE USER&nbsp;</strong>is the individual using our Service.
          The User corresponds to the Data Subject, who is the subject of
          Personal Data.
        </p>
        <ol start={3}>
          <li>
            <strong>
              <u>Information Collection and Use</u>
            </strong>
          </li>
        </ol>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
        <ol start={4}>
          <li>
            <strong>
              <u>Types of Data Collected</u>
            </strong>
          </li>
        </ol>
        <p>
          <strong>Personal Data</strong>
        </p>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (&ldquo;<strong>Personal Data</strong>&rdquo;).
          Personally identifiable information may include, but is not limited
          to:
        </p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Cookies and Usage Data</li>
        </ul>
        <p>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us&nbsp;by following the unsubscribe link.
        </p>
        <p>
          <strong>Usage Data</strong>
        </p>
        <p>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through a mobile
          device (&ldquo;<strong>Usage Data</strong>&rdquo;).
        </p>
        <p>
          This Usage Data may include information such as your computer's
          Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.
        </p>
        <p>
          When you access Service with a mobile device, this Usage Data may
          include information such as the type of mobile device you use, your
          mobile device unique ID, the IP address of your mobile device, your
          mobile operating system, the type of mobile Internet browser you use,
          unique device identifiers and other diagnostic data.
        </p>
        <p>
          <strong>Tracking Cookies Data</strong>
        </p>
        <p>
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </p>
        <p>
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyze our Service.
        </p>
        <p>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>
        <p>Examples of Cookies we use:</p>
        <ul>
          <li>
            <strong>Session Cookies:</strong>We use Session Cookies to operate
            our Service.
          </li>
          <li>
            <strong>Preference Cookies:</strong>We use Preference Cookies to
            remember your preferences and various settings.
          </li>
          <li>
            <strong>Security Cookies:</strong>We use Security Cookies for
            security purposes.
          </li>
          <li>
            <strong>Advertising Cookies:</strong>Advertising Cookies are used to
            serve you with advertisements that may be relevant to you and your
            interests.
          </li>
        </ul>
        <p>
          <strong>Other Data</strong>
        </p>
        <p>
          While using our Service, we may also collect the following
          information: sex, age, date of birth, place of birth, passport
          details, citizenship, registration at place of residence and actual
          address, telephone number (work, mobile), details of documents on
          education, qualification, professional training, employment
          agreements, non-disclosure agreements, information on bonuses and
          compensation, information on marital status, family members, social
          security (or other taxpayer identification) number, office location
          and other data.
        </p>
        <ol start={5}>
          <li>
            <strong>
              <u>Use of Data</u>
            </strong>
          </li>
        </ol>
        <p>UpStamps&nbsp;uses the collected data for various purposes:</p>
        <ul>
          <li>to provide and maintain our Service;</li>
          <li>to notify you about changes to our Service;</li>
          <li>
            to allow you to participate in interactive features of our Service
            when you choose to do so;
          </li>
          <li>to provide customer support;</li>
          <li>
            to gather analysis or valuable information so that we can improve
            our Service;
          </li>
          <li>to monitor the usage of our Service;</li>
          <li>to detect, prevent and address technical issues;</li>
          <li>to fulfill any other purpose for which you provide it;</li>
          <li>
            to carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection;
          </li>
          <li>
            to provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.;
          </li>
          <li>
            to provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </li>
          <li>
            in any other way we may describe when you provide the information;
          </li>
          <li>for any other purpose with your consent.</li>
        </ul>
        <ol start={6}>
          <li>
            <strong>
              <u>Retention of Data</u>
            </strong>
          </li>
        </ol>
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>
        <ol start={7}>
          <li>
            <strong>
              <u>Transfer of Data</u>
            </strong>
          </li>
        </ol>
        <p>
          Your information, including Personal Data, may be transferred to
          &ndash; and maintained on &ndash; computers located outside of your
          state, province, country or other governmental jurisdiction where the
          data protection laws may differ from those of your jurisdiction.
        </p>
        <p>
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          UpStamps&nbsp;will take all the steps reasonably necessary to ensure
          that your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>
        <ol start={8}>
          <li>
            <strong>
              <u>Disclosure of Data</u>
            </strong>
          </li>
        </ol>
        <p>
          We may disclose personal information that we collect, or you provide:
        </p>
        <ul>
          <li>
            <strong>Disclosure for Law Enforcement.</strong>
          </li>
        </ul>
        <p>
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities.
        </p>
        <ul>
          <li>
            <strong>Business Transaction.</strong>
          </li>
        </ul>
        <p>
          If we or our subsidiaries are involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred.
        </p>
        <ul>
          <li>
            <strong>Other cases. We may disclose your information also:</strong>
          </li>
        </ul>
        <p>to our subsidiaries and affiliates;</p>
        <ol start={9}>
          <li>
            <strong>
              <u>Security of Data</u>
            </strong>
          </li>
        </ol>
        <p>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
        <ol start={10}>
          <li>
            <strong>
              <u>
                Your Data Protection Rights Under General Data Protection
                Regulation (GDPR)
              </u>
            </strong>
          </li>
        </ol>
        <p>
          If you are a resident of the European Union (EU) and European Economic
          Area (EEA), you have certain data protection rights, covered by GDPR.
          &ndash; See more at https://eur-lex.europa.eu/eli/reg/2016/679/oj
        </p>
        <p>
          We aim to take reasonable steps to allow you to correct, amend,
          delete, or limit the use of your Personal Data.
        </p>
        <p>
          If you wish to be informed what Personal Data we hold about you and if
          you want it to be removed from our systems, please email us at &nbsp;
          <a href="mailto:info@upstamps.com">info@upstamps.com</a>
        </p>
        <p>
          In certain circumstances, you have the following data protection
          rights:
        </p>
        <ul>
          <li>
            the right to access, update or to delete the information we have on
            you;
          </li>
          <li>
            the right of rectification. You have the right to have your
            information rectified if that information is inaccurate or
            incomplete;
          </li>
          <li>
            the right to object. You have the right to object to our processing
            of your Personal Data;
          </li>
          <li>
            the right of restriction. You have the right to request that we
            restrict the processing of your personal information;
          </li>
          <li>
            the right to data portability. You have the right to be provided
            with a copy of your Personal Data in a structured, machine-readable
            and commonly used format;
          </li>
          <li>
            the right to withdraw consent.&nbsp;You also have the right to
            withdraw your consent at any time where we rely on your consent to
            process your personal information;
          </li>
        </ul>
        <p>
          Please note that we may ask you to verify your identity before
          responding to such requests. Please note, we may not able to provide
          Service without some necessary data.
        </p>
        <p>
          You have the right to complain to a Data Protection Authority about
          our collection and use of your Personal Data. For more information,
          please contact your local data protection authority in the European
          Economic Area (EEA).
        </p>
        <ol start={11}>
          <li>
            <strong>
              <u>
                Your Data Protection Rights under the California Privacy
                Protection Act (CalOPPA)
              </u>
            </strong>
          </li>
        </ol>
        <p>
          CalOPPA is the first state law in the nation to require commercial
          websites and online services to post a privacy policy. The law&rsquo;s
          reach stretches well beyond California to require a person or company
          in the United States (and conceivable the world) that operates
          websites collecting personally identifiable information from
          California consumers to post a conspicuous privacy policy on its
          website stating exactly the information being collected and those
          individuals with whom it is being shared, and to comply with this
          policy. &ndash; See more at: &nbsp;
          <a
            rel="noopener noreferrer"
            href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/"
            target="_blank"
          >
            https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/
          </a>
        </p>
        <p>According to CalOPPA we agree to the following:</p>
        <ul>
          <li>users can visit our site anonymously;</li>
          <li>
            our Privacy Policy link includes the word &ldquo;Privacy&rdquo;, and
            can easily be found on the page specified above on the home page of
            our website;
          </li>
          <li>
            users will be notified of any privacy policy changes on our Privacy
            Policy Page;
          </li>
          <li>
            users are able to change their personal information by emailing us
            at &nbsp;<a href="mailto:info@upstamps.com">info@upstamps.com</a>.
          </li>
        </ul>
        <p>Our Policy on &ldquo;Do Not Track&rdquo; Signals:</p>
        <p>
          We honor Do Not Track signals and do not track, plant cookies, or use
          advertising when a Do Not Track browser mechanism is in place. Do Not
          Track is a preference you can set in your web browser to inform
          websites that you do not want to be tracked.
        </p>
        <p>
          You can enable or disable Do Not Track by visiting the Preferences or
          Settings page of your web browser.
        </p>
        <ol start={12}>
          <li>
            <strong>
              <u>Service Providers</u>
            </strong>
          </li>
        </ol>
        <p>
          We may employ third party companies and individuals to facilitate our
          Service (&ldquo;<strong>Service Providers</strong>&rdquo;), provide
          Service on our behalf, perform Service-related services or assist us
          in analysing how our Service is used.
        </p>
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>
        <ol start={13}>
          <li>
            <strong>
              <u>Analytics</u>
            </strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
        </p>
        <p>
          <strong>Simple Analytics</strong>
        </p>
        <p>
          Simple Analytics is a web analytics service that tracks and reports
          website traffic. Simple Analytics uses the data collected to track and
          monitor the use of our Service.
        </p>
        <p>
          For more information on the privacy practices of Simple Analytics,
          please visit the Simple Analytics Privacy Terms web page:&nbsp;
          <a
            rel="noopener noreferrer"
            href="https://simpleanalytics.com/privacy"
            target="_blank"
          >
            https://simpleanalytics.com/privacy
          </a>
        </p>
        <p>
          We also encourage you to review the Google's policy for safeguarding
          your data:&nbsp;
          <a
            rel="noopener noreferrer"
            href=" https://support.google.com/analytics/answer/6004245"
            target="_blank"
          >
            https://support.google.com/analytics/answer/6004245
          </a>
          .
        </p>
        <p>
          <strong>Cloudflare analytics</strong>
        </p>
        <p>
          Cloudflare analytics is a web analytics service operated by Cloudflare
          Inc. Read the Privacy Policy here:&nbsp;
          <a
            rel="noopener noreferrer"
            href=" https://www.cloudflare.com/privacypolicy/"
            target="_blank"
          >
            https://www.cloudflare.com/privacypolicy/
          </a>
        </p>

        <ol start={14}>
          <li>
            <strong>
              <u>CI/CD tools</u>
            </strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to automate the development
          process of our Service.
        </p>
        <p>
          <strong>GitHub</strong>
        </p>
        <p>GitHub is provided by GitHub, Inc.</p>
        <p>
          GitHub is a development platform to host and review code, manage
          projects, and build software.
        </p>
        <p>
          For more information on what data GitHub collects for what purpose and
          how the protection of the data is ensured, please visit GitHub Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://help.github.com/en/articles/github-privacy-statement"
          >
            https://help.github.com/en/articles/github-privacy-statement.
          </a>
        </p>
        <p>
          <strong>Travis CI</strong>
        </p>
        <p>
          Travis CI is a distributed continuous integration service to build and
          test projects hosted at GitHub.
        </p>
        <p>
          For more information on what data Travis CI collects for what purpose
          and how the protection of the data is ensured, please visit Travis CI
          Privacy Policy page: &nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://docs.travis-ci.com/legal/privacy-policy"
          >
            https://docs.travis-ci.com/legal/privacy-policy.
          </a>
        </p>
        <p>
          <strong>Codacy</strong>
        </p>
        <p>
          Codacy is an automated code analysis/quality tool that helps
          developers ship better software, faster.
        </p>
        <p>
          For more information on what data Codacy collect for what purpose and
          how the protection of the data is ensured, please visit Codacy Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            href="https://www.codacy.com/privacy"
            target="_blank"
          >
            https://www.codacy.com/privacy.
          </a>
        </p>

        <ol start={15}>
          <li>
            <strong>
              <u>Communication tools</u>
            </strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to automate the communication
          and feedback process of our Service.
        </p>
        <p>
          <strong>Customerly</strong>
        </p>
        <p>Customerly is provided by Customerly Ltd.</p>
        <p>
          Customerly is a customer service software for Live Chat, Video Calls,
          Typing previews, Knowledgebase & Surveys. Customerly is the all-in-one
          platform with a simple goal: to bridge the gap between you and your
          customers
        </p>
        <p>
          For more information on what data Customerly collects for what purpose
          and how the protection of the data is ensured, please visit Customerly
          Privacy Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://www.customerly.io/en/privacy"
          >
            https://www.customerly.io/en/privacy
          </a>
        </p>

        <ol start={16}>
          <li>
            <strong>
              <u>Cloud, Authentication and Hosting tools</u>
            </strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to automate hosting,
          authentication and cloud process of our Service.
        </p>
        <p>
          <strong>Heroku</strong>
        </p>
        <p>Heroku is provided by Salesforce.</p>
        <p>
          Heroku focuses relentlessly on apps and the developer experience
          around apps. Heroku lets companies of all sizes embrace the value of
          apps, not the distraction of hardware, nor the distraction of servers
          - virtual or otherwise.
        </p>
        <p>
          For more information on what data Heroku collects for what purpose and
          how the protection of the data is ensured, please visit Heroku Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://www.salesforce.com/company/privacy/"
          >
            https://www.salesforce.com/company/privacy/
          </a>
        </p>

        <p>
          <strong>Hasura</strong>
        </p>
        <p>Hasura is provided by Hasura, inc.</p>
        <p>
          Hasura is an open source engine that connects to your databases &
          microservices and auto-generates a production-ready GraphQL backend.
        </p>
        <p>
          For more information on what data Hasura collects for what purpose and
          how the protection of the data is ensured, please visit Hasura Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://hasura.io/legal/hasura-privacy-policy/"
          >
            https://hasura.io/legal/hasura-privacy-policy/
          </a>
        </p>

        <p>
          <strong>Zeit</strong>
        </p>
        <p>Zeit is provided by Zeit, inc.</p>
        <p>
          ZEIT is a platform for Static and Jamstack deployment, Serverless
          Functions, and Global CDN.
        </p>
        <p>
          For more information on what data Zeit collects for what purpose and
          how the protection of the data is ensured, please visit Zeit Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://zeit.co/legal/privacy-policy"
          >
            https://zeit.co/legal/privacy-policy
          </a>
        </p>

        <p>
          <strong>Auth0</strong>
        </p>
        <p>Auth0 is provided by Auth0, inc.</p>
        <p>
          Auth0 is a authentication and authorization platform for web, mobile,
          and legacy applications so you can focus on your core business.
        </p>
        <p>
          For more information on what data Auth0 collects for what purpose and
          how the protection of the data is ensured, please visit Auth0 Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://auth0.com/privacy/"
          >
            https://auth0.com/privacy/
          </a>
        </p>

        <p>
          <strong>Surge</strong>
        </p>
        <p>Surge is provided by Surge.</p>
        <p>Surge is a Static web publishing for Front-End Developers</p>
        <p>
          For more information on what data Surge collects for what purpose and
          how the protection of the data is ensured, please visit Surge Privacy
          Policy page:&nbsp;
          <a
            rel="noopener noreferrer"
            target="_blank"
            href="https://surge.sh/privacy"
          >
            https://surge.sh/privacy
          </a>
        </p>

        <ol start={17}>
          <li>
            <strong>
              <u>Payments</u>
            </strong>
          </li>
        </ol>
        <p>
          We may provide paid products and/or services within Service. In that
          case, we use third-party services for payment processing (e.g. payment
          processors).
        </p>
        <p>
          We will not store or collect your payment card details. That
          information is provided directly to our third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by
          PCI-DSS as managed by the PCI Security Standards Council, which is a
          joint effort of brands like Visa, Mastercard, American Express and
          Discover. PCI-DSS requirements help ensure the secure handling of
          payment information.
        </p>
        <p>The payment processors we work with are:</p>
        <p>Stripe:</p>
        <p>
          Their Privacy Policy can be viewed at: https://stripe.com/us/privacy
        </p>
        <ol start={18}>
          <li>
            <strong>
              <u>Links to Other Sites</u>
            </strong>
          </li>
        </ol>
        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party's site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <ol start={19}>
          <li>
            <strong>
              <u>Children's Privacy</u>
            </strong>
          </li>
        </ol>
        <p>
          Our Services are not intended for use by children under the age of 18
          (&ldquo;<strong>Child</strong>&rdquo; or &ldquo;
          <strong>Children</strong>&rdquo;).
        </p>
        <p>
          We do not knowingly collect personally identifiable information from
          Children under 18. If you become aware that a Child has provided us
          with Personal Data, please contact us. If we become aware that we have
          collected Personal Data from Children without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>
        <ol start={20}>
          <li>
            <strong>
              <u>Changes to This Privacy Policy</u>
            </strong>
          </li>
        </ol>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update
          &ldquo;effective date&rdquo; at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <ol start={21}>
          <li>
            <strong>
              <u>Contact Us</u>
            </strong>
          </li>
        </ol>
        <p>
          If you have any questions about this Privacy Policy, please contact
          us:
        </p>
        <p>
          By email: <a href="mailto:info@upstamps.com">info@upstamps.com</a>
        </p>
      </div>
    </div>
  );
}

export default styled(Privacy)`
  ${DocumentStyles}
`;
